# 1. Reading and Writing Data

We are going to use a dataset that contains **how many characters** are found in each book by our four authors (Charles Dickens, Elizabeth Gaskell, Edith Wharton, and Mark Twain). After that we are going to do some data analytics to try to find out if we can see some patterns in terms of geography (some similitudes in number of characters in Brittish vs. US authors).

First, let's import our two libraries: Pandas and Numpy

In [5]:
#Your code in here

In [14]:
#Solution
import pandas as pd
import numpy as np

Now:
   * 1) Open "dickens_characters.csv" with pandas. Save it into a variable and print it to inspect it. Remember to add the argument index_col = 0 (to avoid having an annoying extra column).
   * 2) Open "dickens.csv" with numpy. Save it into a variable and print it to inspect it. Remember to add the arguments delimiter = "," and dtype = str to avoid having weird encoding issues.
   * 3) Select in both cases the column "Number of Characters" and save it into a new variable.
   * 4) Check the data tpe of the first element in the list/array in both lists. 
   * 5) Transform the numpy str data type into am integer data type.

In [15]:
# Your code here

In [18]:
# Solution 1
dickens_pandas = pd.read_csv("dickens_characters.csv", index_col = 0)
dickens_pandas

Titles  Number of Characters
0      A Christmas Carol                    68
1   A Tale of Two Cities                   160
2          Barnaby Rudge                   246
3            Bleak House                   444
4      David Copperfield                   442
5         Dombey and Son                   481
6     Great Expectations                   278
7             Hard Times                   162
8          Little Dorrit                   467
9      Martin Chuzzlewit                   476
10     Nicholas Nickleby                   422
11         Old Curiosity                   237
12          Oliver Twist                   172
13     Our Mutual Friend                   574
14    The Battle of Life                    69
15            The Chimes                    63
16           The Cricket                    64
17       The Haunted Man                    63
18   The Pickwick Papers                   525

In [19]:
# Solution 2
dickens = np.genfromtxt("dickens_characters.csv", delimiter=",", dtype = str)
dickens

array([['', 'Titles', 'Number of Characters'],
       ['0', 'A Christmas Carol', '68'],
       ['1', 'A Tale of Two Cities', '160'],
       ['2', 'Barnaby Rudge', '246'],
       ['3', 'Bleak House', '444'],
       ['4', 'David Copperfield', '442'],
       ['5', 'Dombey and Son', '481'],
       ['6', 'Great Expectations', '278'],
       ['7', 'Hard Times', '162'],
       ['8', 'Little Dorrit', '467'],
       ['9', 'Martin Chuzzlewit', '476'],
       ['10', 'Nicholas Nickleby', '422'],
       ['11', 'Old Curiosity', '237'],
       ['12', 'Oliver Twist', '172'],
       ['13', 'Our Mutual Friend', '574'],
       ['14', 'The Battle of Life', '69'],
       ['15', 'The Chimes', '63'],
       ['16', 'The Cricket', '64'],
       ['17', 'The Haunted Man', '63'],
       ['18', 'The Pickwick Papers', '525']], dtype='<U20')

In [21]:
# Solution 3
characters_pandas = dickens_pandas["Number of Characters"].to_list()
print(characters_pandas)

[68, 160, 246, 444, 442, 481, 278, 162, 467, 476, 422, 237, 172, 574, 69, 63, 64, 63, 525]


In [23]:
characters_numpy = dickens[1:, 2]
characters_numpy

array(['68', '160', '246', '444', '442', '481', '278', '162', '467',
       '476', '422', '237', '172', '574', '69', '63', '64', '63', '525'],
      dtype='<U20')

In [25]:
#Solution 4
type(characters_pandas[0])

int

In [26]:
type(characters_numpy[0])

numpy.str_

In [28]:
#Solution 5
characters_dickens = characters_numpy.astype(int) #we have to transform that into integers
characters_dickens

array([ 68, 160, 246, 444, 442, 481, 278, 162, 467, 476, 422, 237, 172,
       574,  69,  63,  64,  63, 525])

Great! It is clear that numpy and pandas can open csv files but they both do different things! Now repeat the same operation with the other 3 authors. That means:
   * 1) Open the 3 csv files using numpy and store them into a variable. 
   * 2) Create 3 new variables storing only the column of the years
   * 3) Convert the strings of those years into integers and store them into variables (and be consistent with the names!).
   * 4) Print the 4 variables with the number of characters per author (Dickens, Gaskell, Wharton, Twain).

In [30]:
#Your code in here

In [31]:
#Solution 1
gaskell = np.genfromtxt("gaskell_characters.csv", delimiter=",", dtype = str)
wharton = np.genfromtxt("wharton_characters.csv", delimiter=",", dtype = str)
twain = np.genfromtxt("twain_characters.csv", delimiter=",", dtype = str)

In [32]:
#Solution 2
characters_gaskell_a = gaskell[1:, 2]
characters_wharton_a = wharton[1:, 2]
characters_twain_a = twain[1:, 2]

In [33]:
#Solution 3
characters_gaskell = characters_gaskell_a.astype(int) 
characters_wharton = characters_wharton_a.astype(int) 
characters_twain =  characters_twain_a.astype(int) 

In [34]:
#Solution 4
characters_dickens

array([ 68, 160, 246, 444, 442, 481, 278, 162, 467, 476, 422, 237, 172,
       574,  69,  63,  64,  63, 525])

In [35]:
characters_gaskell

array([141, 205, 290, 202, 311, 214, 286, 414])

In [36]:
characters_wharton

array([187,  79, 298, 156, 229, 157, 164, 198, 152,  97, 325, 164])

In [37]:
characters_twain

array([227,  66, 155, 132, 169, 422,  56, 149, 154,  70,  60])

Great! Now we have our data open and ready to do some data analytics :)

# 2. Aggregations

Let's use aggregations to do some quick mathematical operations on our number of characters to find out some patterns in terms of the geographical origin of our authors!

Please do:
   * 1) Compute the total number of elements (i.e. number of characters) in the 4 variables (Dickens, Gaskell, Wharton, Twain). Use np.sum to do that. Create two numpy arrays, one called total_characters_US and the other one total_characters_UK. Put first the male number, and second the female one (so we can also do some gender analytics).
   * 2) Repeat the same operation with np.max to find out the maximum number of characters per author (and create two arrays with that information storing first the male author and then the female author).

In [49]:
# Your code in here

In [39]:
# Solution 1

print(np.sum(characters_dickens))
print(np.sum(characters_gaskell))

5413
2063


In [40]:
total_characters_UK = np.array([5413, 2063])

In [43]:
print(np.sum(characters_twain))
print(np.sum(characters_wharton))

1660
2206


In [44]:
total_characters_US = np.array([1660, 2206])

In [45]:
# Solution 2
print(np.max(characters_dickens))
print(np.max(characters_gaskell))

574
414


In [46]:
max_characters_UK = np.array([574, 414])

In [47]:
print(np.max(characters_twain))
print(np.max(characters_wharton))

422
325


In [48]:
max_characters_US = np.array([574, 414])

# 3. Comparison Operators

Let's now use some comparison operators to see which authors wrote more number of characters in their books, and if we can see any patterns in terms of gender or geography.

Please do:
   * 1) Compare total_characters_UK and total_characters_US using np.greater (choose whatever order you like, i.e. check if the US number of characters is bigger than the UK or the other way around). What do you see? And: do female or male authors write more characters?
   * 2) If you would like to compare the total number of characters in terms of geography (so, male + female both US and UK) how would you do that?
   * 3) Repeat the same operation with the maximum number of characters (both points 1 and 2).

In [50]:
# Your code in here

In [51]:
# Solution 1

np.greater(total_characters_UK, total_characters_US) 

array([ True, False])

This output is telling us that Charles Dickens (UK) has more characters in his books than Mark Twain (US), but Edith Wharton (US) has more characters than Elizabeth Gaskell (US). Remeber that we used position 1 for male characters and position 2 for female characters!

In [52]:
# Solution 2
np.greater(np.sum(total_characters_UK), np.sum(total_characters_US))

True

That output is telling us that overall, if we sum Charles Dickens + Elizabeth Gaskell and Mark Twain + Edith Wharton, we are getting a higher number of characters in the UK rather than in the US.

In [53]:
# Solution 3.
np.greater(max_characters_UK, max_characters_US)

array([False, False])

That output is telling us that Charles Dickens has less max characters than Mark Twain and Elizabeth Gaskell has less max characters than Edith Wharton. So: the US has actually a higher peak of maximum number of characters in a book even if the UK has a total higher number of characters overall

In [54]:
np.greater(np.sum(max_characters_UK), np.sum(max_characters_US))

False

And that just confirmed what we just saw in the previous line of code!

# 4. Opening and saving data

Let's now go one step behind and let's use our original total number of characters arrays. Let's just select Charles Dickens (characters_dickens). And now:
   * 1. Let's calculate the mean amount of characters per author using np.mean. Store that in a variable.
   * 2. Now, check how many books did Dickens write above the mean and behind the mean. Use np.less_equal and np.greater_equal.
   * 3. Use np.count_nonzero() to see how many positives (True values) you have in each above and below to see if Dickens was more prone to write books with a higher volume of characters above average or not really.
   * 4. Save that into a variable using an np.array format.
   * 5. Now, use np.savetxt() to save that variable into a txt file. Remember to use it following this order: np.savetxt("file_name.txt", variable,  fmt='%d', encoding = "Utf-8") #it is very important we include fmt %d!
   * 6. Check the file that just got saved into your Jupyter Notebooks interface. Open it. Check also that same file in your local computer file system.
   * 7. Now use np.loadtxt("file_name.txt") to upload that file again.
   * 8. Let's imagine that you want to save Solution 1 of the previous activity you just did (comparing the total number of characters UK vs. US male vs. female writers). Please store that value into a variable.
   * 9. Try to save that using the same np.savetxt("file_name.txt", variable,  fmt='%d', encoding = "Utf-8"). Check that file in Jupyter Notebooks. What happens?

In [59]:
# Solution 1
mean_dickens = np.mean(characters_dickens)
mean_dickens

284.89473684210526

In [61]:
# Solution 2
above_average = np.greater_equal(characters_dickens, mean_dickens)
above_average

array([False, False, False,  True,  True,  True, False, False,  True,
        True,  True, False, False,  True, False, False, False, False,
        True])

In [62]:
below_average = np.less_equal(characters_dickens, mean_dickens)
below_average

array([ True,  True,  True, False, False, False,  True,  True, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
       False])

In [63]:
# Solution 3
np.count_nonzero(above_average)

8

In [64]:
np.count_nonzero(below_average) #So dickens had more books with less characters on average

11

In [65]:
# Solution 4
dickens_characters_analytics = np.array([8, 11])

In [66]:
# Solution 5
np.savetxt("dickens_characters_analytics.txt", dickens_characters_analytics,  fmt='%d', encoding = "Utf-8") 

In [67]:
# Solution 7
np.loadtxt("dickens_characters_analytics.txt")

array([ 8., 11.])

In [68]:
# Solution 8
comparison_UK_US = np.greater(total_characters_UK, total_characters_US) 
comparison_UK_US

array([ True, False])

In [69]:
# Solution 9.
np.savetxt("comparison_UK_US.txt", comparison_UK_US,  fmt='%d', encoding = "Utf-8")