# 1. Numpy Arrays Dimensionality

Let's start by learning how to create n-dimensions (1, 2, 3) different arrays!

First the libraries Pandas and Numpy have been imported for you

In [1]:
import pandas as pd
import numpy as np

Let's have a look at a dataset that contains the total and unique number of words of each novel written by Elizabeth Gaskell

In [3]:
data = pd.read_csv("Gaskell_number_words.csv", index_col = 0)
data

Titles  Total Words  Unique Words
0  A Dark Night's Work        33494          6266
1             Cranford        33281          7021
2          Mary Barton        84552         10425
3       My Lady Ludlow        35421          6978
4      North and South        84889         11676
5                 Ruth        81049          9835
6      Sylvia's Lovers        96870         11900
7  Wives and Daughters       139209         12037

The Total and Unique words columns have been selected for you into python lists.

In [5]:
total_words = data["Total Words"].to_list()
total_words

[33494, 33281, 84552, 35421, 84889, 81049, 96870, 139209]

In [11]:
total_unique_words = data["Unique Words"].to_list()
total_unique_words

[6266, 7021, 10425, 6978, 11676, 9835, 11900, 12037]

In [46]:
titles = data["Titles"].to_list()
titles

["A Dark Night's Work",
 'Cranford',
 'Mary Barton',
 'My Lady Ludlow',
 'North and South',
 'Ruth',
 "Sylvia's Lovers",
 'Wives and Daughters']

Now:
   * Create a 1 dimension numpy array using the values found in total_words.
   * Use the .ndim method to check its dimensions
   * Use the .shape method to check its shape
   * Use the .size method to check its lengh

In [12]:
gaskell_words = np.array([33494, 33281, 84552, 35421, 84889, 81049, 96870, 139209])
gaskell_words

array([ 33494,  33281,  84552,  35421,  84889,  81049,  96870, 139209])

In [16]:
# your code in here

In [17]:
# Solution
gaskell_words.ndim

1

In [14]:
gaskell_words.shape

(8,)

In [15]:
gaskell_words.size

8

And now:
   * Create a 2 dimension numpy array using the values found in total words and in unqiue words.
   * Use the .ndim method to check its dimensions
   * use the .shape method to check its shape
   * use the .size method to check its lenght

In [26]:
# Your code in here

In [27]:
# Solution
gaskell_two_dim_vector = np.array([
    [33494, 33281, 84552, 35421, 84889, 81049, 96870, 139209],
    [6266, 7021, 10425, 6978, 11676, 9835, 11900, 12037]
])

In [22]:
gaskell_two_dim_vector

array([[ 33494,  33281,  84552,  35421,  84889,  81049,  96870, 139209],
       [  6266,   7021,  10425,   6978,  11676,   9835,  11900,  12037]])

In [23]:
gaskell_two_dim_vector.ndim

2

In [24]:
gaskell_two_dim_vector.shape

(2, 8)

In [25]:
gaskell_two_dim_vector.size

16

**Important**. We can very easily transform a python list(s) into a numpy array(s) in just one line of code

In [34]:
new_array = np.array(total_words)
new_array

array([ 33494,  33281,  84552,  35421,  84889,  81049,  96870, 139209])

In [35]:
new_two_dim_array = np.array([total_words, total_unique_words])
new_two_dim_array

array([[ 33494,  33281,  84552,  35421,  84889,  81049,  96870, 139209],
       [  6266,   7021,  10425,   6978,  11676,   9835,  11900,  12037]])

# 2. Slicing

Now that we have our array containing our two rows with both number of total and unique number of words, let's practice how to do some slicing!
   * Select two rows and the firt 3 columns
   * Now select 1 row and the last 4 columns
   * Change the order of both columns and rows in reverse (so, row 2 is now row 1 and the last column is the first and all the order is changed
   * Just select the first column
   * Just select the first row using two different ways of doing it

In [44]:
# Your code in here

In [45]:
# Solution
gaskell_two_dim_vector[:2,:3]

array([[33494, 33281, 84552],
       [ 6266,  7021, 10425]])

In [39]:
gaskell_two_dim_vector[:1, 4:]

array([[ 84889,  81049,  96870, 139209]])

In [40]:
gaskell_two_dim_vector[::-1, ::-1]

array([[ 12037,  11900,   9835,  11676,   6978,  10425,   7021,   6266],
       [139209,  96870,  81049,  84889,  35421,  84552,  33281,  33494]])

In [41]:
gaskell_two_dim_vector[:, 0]

array([33494,  6266])

In [42]:
gaskell_two_dim_vector[0, :]

array([ 33494,  33281,  84552,  35421,  84889,  81049,  96870, 139209])

In [43]:
gaskell_two_dim_vector[0]

array([ 33494,  33281,  84552,  35421,  84889,  81049,  96870, 139209])

# 3. Concatenating and Splitting

Let's print once again the variables that were given to you at the beginning of this notebook:

In [47]:
total_words

[33494, 33281, 84552, 35421, 84889, 81049, 96870, 139209]

In [48]:
total_unique_words

[6266, 7021, 10425, 6978, 11676, 9835, 11900, 12037]

In [49]:
titles

["A Dark Night's Work",
 'Cranford',
 'Mary Barton',
 'My Lady Ludlow',
 'North and South',
 'Ruth',
 "Sylvia's Lovers",
 'Wives and Daughters']

Now:
 * Convert the three of them into 3 separate arrays storing them in 3 different variables.
 * Concatenate the three of them and store it into a new variable.
 * Check the shape of your new array using the shape method.
 * Create a new array using the method np.arange() with numbers matching the shape of the two-dim array that you have just created but using non-consecutive numbers (i.e. 2-4-6-8...). The number range and the stop gap between numbers is up to you!
 * And now get split your newly created numpy array creating two lists: the first one has the first 3 rows and the second list has the last row with those numbers that you have just added. Check the new variable data type and length.
 * Finally, go back to the variable where you had a numpy array with 4 rows (the one you created with np.concatenate()). Now drop entirely the last row. Check the type and lenght of the new variable.

In [ ]:
#Your code in here

In [50]:
# Solution
np_array_1 = np.array(total_words)
np_array_1

array([ 33494,  33281,  84552,  35421,  84889,  81049,  96870, 139209])

In [51]:
np_array_2 = np.array(total_unique_words)
np_array_2

array([ 6266,  7021, 10425,  6978, 11676,  9835, 11900, 12037])

In [52]:
np_array_3 = np.array(titles)
np_array_3

array(["A Dark Night's Work", 'Cranford', 'Mary Barton', 'My Lady Ludlow',
       'North and South', 'Ruth', "Sylvia's Lovers",
       'Wives and Daughters'], dtype='<U19')

In [57]:
new_array = np.concatenate([[np_array_1], [np_array_2], [np_array_3]], axis = 0)
new_array

array([['33494', '33281', '84552', '35421', '84889', '81049', '96870',
        '139209'],
       ['6266', '7021', '10425', '6978', '11676', '9835', '11900',
        '12037'],
       ["A Dark Night's Work", 'Cranford', 'Mary Barton',
        'My Lady Ludlow', 'North and South', 'Ruth', "Sylvia's Lovers",
        'Wives and Daughters']], dtype='<U19')

In [58]:
new_array.shape

(3, 8)

In [60]:
np_array_4 = np.arange(0, 16, 2)
np_array_4

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [64]:
new_array_b = np.concatenate([new_array, [np_array_4]], axis=0)
new_array_b

array([['33494', '33281', '84552', '35421', '84889', '81049', '96870',
        '139209'],
       ['6266', '7021', '10425', '6978', '11676', '9835', '11900',
        '12037'],
       ["A Dark Night's Work", 'Cranford', 'Mary Barton',
        'My Lady Ludlow', 'North and South', 'Ruth', "Sylvia's Lovers",
        'Wives and Daughters'],
       ['0', '2', '4', '6', '8', '10', '12', '14']], dtype='<U19')

In [67]:
split_array = np.split(new_array_b, [3], axis = 0)
split_array

[array([['33494', '33281', '84552', '35421', '84889', '81049', '96870',
         '139209'],
        ['6266', '7021', '10425', '6978', '11676', '9835', '11900',
         '12037'],
        ["A Dark Night's Work", 'Cranford', 'Mary Barton',
         'My Lady Ludlow', 'North and South', 'Ruth', "Sylvia's Lovers",
         'Wives and Daughters']], dtype='<U19'),
 array([['0', '2', '4', '6', '8', '10', '12', '14']], dtype='<U19')]

In [69]:
type(split_array)

list

In [70]:
len(split_array)

2

In [72]:
drop_away = np.delete(new_array_b, [3], axis = 0)
drop_away

array([['33494', '33281', '84552', '35421', '84889', '81049', '96870',
        '139209'],
       ['6266', '7021', '10425', '6978', '11676', '9835', '11900',
        '12037'],
       ["A Dark Night's Work", 'Cranford', 'Mary Barton',
        'My Lady Ludlow', 'North and South', 'Ruth', "Sylvia's Lovers",
        'Wives and Daughters']], dtype='<U19')

In [73]:
type(drop_away)

numpy.ndarray

In [74]:
len(drop_away)

3

# Some extra knowledge

If we compare our csv pandas data frame with our numpy array we can see that, in transforming the data, the whole rows and columns arrangement has been changed.

In [75]:
data

Titles  Total Words  Unique Words
0  A Dark Night's Work        33494          6266
1             Cranford        33281          7021
2          Mary Barton        84552         10425
3       My Lady Ludlow        35421          6978
4      North and South        84889         11676
5                 Ruth        81049          9835
6      Sylvia's Lovers        96870         11900
7  Wives and Daughters       139209         12037

In [77]:
data_2 = pd.DataFrame(new_array)
data_2

0         1            2               3  \
0                33494     33281        84552           35421   
1                 6266      7021        10425            6978   
2  A Dark Night's Work  Cranford  Mary Barton  My Lady Ludlow   

                 4      5                6                    7  
0            84889  81049            96870               139209  
1            11676   9835            11900                12037  
2  North and South   Ruth  Sylvia's Lovers  Wives and Daughters

This is due to the different functionalities between pandas datafarmes and numpy arrays. This is due to the fact that Numpy arrays are mostly used as vectors to feed machine learning algorithms. That being said, there is a method called "Transpose" (.T), that allows us to switch our numpy array very easily and fast for visualization purposes if we need that.

In [78]:
data_2.T

0      1                    2
0   33494   6266  A Dark Night's Work
1   33281   7021             Cranford
2   84552  10425          Mary Barton
3   35421   6978       My Lady Ludlow
4   84889  11676      North and South
5   81049   9835                 Ruth
6   96870  11900      Sylvia's Lovers
7  139209  12037  Wives and Daughters